baseURL = "https://MiladMohammadi.com"
# [en, zh-cn, fr, pl, ...] determines default content language
# [en, zh-cn, fr, pl, ...] 设置默认的语言
defaultContentLanguage = "en"
languageCode = "en-us"
# MissingTranslationPlaceholders = false
#defaultContentLanguageInSubdir = true

# website title
# 网站标题
title = "Milad Mohammadi"

# whether to use robots.txt
# 是否使用 robots.txt
enableRobotsTXT = true
#disableKinds = ["taxonomy-terms"]

# whether to use git commit log
# 是否使用 git 信息
enableGitInfo = true

# whether to use emoji code
# 是否使用 emoji 代码
enableEmoji = true

# ignore some build errors
# 忽略一些构建错误
# ignoreErrors = ["error-remote-getjson", "error-missing-instagram-accesstoken"]

# theme
# 主题
theme = "DoIt"
# themes directory
# 主题目录
#themesDir = "themes"

# Or, when using theme as hugo module
# [module]
# [[module.imports]]
# path = "github.com/HEIGE-PCloud/DoIt"



[params]
  # DoIt theme version
  version = "0.3.X"
  # website title
  title = "Milad Mohammadi Personal WebSite"
  # site description
  description = "Embedded System and Electronic"
  # site keywords
  keywords = ["linux", "kernel", "Electronic", "Embedded", "MicroController"]
  # site default theme ("light", "dark", "black", "auto")
  defaultTheme = "dark"
  # public git repo url only then enableGitInfo is true
  gitRepo = ""
  # which hash function used for SRI, when empty, no SRI is used ("sha256", "sha384", "sha512", "md5")
  fingerprint = ""
  # date format
  dateFormat = "2024-10-22"
  # website images for Open Graph and Twitter Cards
  # images = ["/images/avatar.webp"]
  images = ["/images/coding.png"]
  # enable PWA
  enablePWA = false
  # license information
  license = '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'
  # [Experimental] Bundle js
  bundle = false

[params.home]
    # amount of RSS pages
    rss = 10

    # Home page profile
    [params.home.profile]
      enable = true
      # Gravatar Email for preferred avatar in home page
      gravatarEmail = ""
      # URL of avatar shown in home page
      # avatarURL = "/images/avatar.webp"
      avatarURL = "/images/coding.png"
      # title shown in home page (HTML format is supported)
      title = "Milad Mohammadi"
      # subtitle shown in home page
      subtitle = "Embedded Systems Engineer"
      # whether to use typeit animation for subtitle
      typeit = false
      # whether to show social links
      social = true
      # disclaimer (HTML format is supported)
      disclaimer = "<p>"

    # Home page posts
    [params.home.posts]
      enable = false
      # special amount of posts in each home posts page
      paginate = 7
      # DoIt DELETED | 0.2.0 replaced with hiddenFromHomePage in params.page
      # default behavior when you don't set "hiddenFromHomePage" in front matter
      defaultHiddenFromHomePage = false

[params.social]
      GitHub = "MiladMohammadi72"
      Linkedin = "MilaMohammadi1993"
      Twitter = "##"
      Instagram = ""
      Facebook = ""
      Telegram = "##"
      Gitlab = ""
      Whatsapp = ""
      Email = "MiladMohammadi_1993@yahoo.com"
      RSS = true

[params.footer]
    enable = true
    # Custom content (HTML format is supported)
    custom = ''
    # whether to show Hugo and theme info
    hugo = false
    # Hosted on (HTML format is supported)
    # <a title="Github Pages" href="https://docs.github.com/en/pages/" target="_blank" rel="noopener noreffer">GitHub Pages</a>
    hostedOn = '' 
    # whether to show copyright info
    copyright = true
    # whether to show the author
    author = true
    # site creation time
    since = 2024
    # ICP info only in China (HTML format is supported)
    icp = ""
    # license info (HTML format is supported)
    license= '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'

# Section (all posts) page config
[params.section]
    # special amount of posts in each section page
    paginate = 20
    # date format (month and day)
    dateFormat = "01-02"
    # amount of RSS pages
    rss = 10
    # recently updated posts settings
    [params.section.recentlyUpdated]
      enable = true
      rss = true
      days = 30
      maxCount = 10

# List (category or tag) page config
[params.list]
    # special amount of posts in each list page
    paginate = 20
    # date format (month and day)
    dateFormat = "01-02"
    # amount of RSS pages
    rss = 10

[params.page]
    # Page style ("normal", "wide")
    pageStyle = "wide"
    # wether to enable series navigation
    seriesNavigation = true
    # whether to enable the fontawesome extended syntax
    fontawesome = true
    
    [params.page.math]
      enable = true
      blockLeftDelimiter = ""
      blockRightDelimiter = ""
      inlineLeftDelimiter = ""
      inlineRightDelimiter = ""
      copy_text = true
      mhchem = true

    [params.page.toc]
      # whether to enable the table of the contents
      enable = true
      # whether to keep the static table of the contents in front of the post
      keepStatic = false
      # whether to make the table of the contents in the sidebar automatically collapsed
      auto = true
    [params.page.code]
      copy = false
      maxShownLines = 100
    [params.page.share]
      enable = true
      Twitter = true
    # DoIt CHANGED | 0.2.0 Comment config
    [params.page.comment]
      enable = false
    # Gitalk comment config
    [params.page.comment.gitalk]
      # DoIt NEW | 0.1.1
      enable = false
      owner = ""
      repo = ""
      clientId = ""
      clientSecret = ""
    # DoIt CHANGED | 0.2.10 Page SEO config
    [params.page.seo]
      # image URL
      images = []
      # Publisher info
      [params.page.seo.publisher]
        name = "Milad Mohammadi"
        logoUrl = ""
    # DoIt NEW | 0.2.14 Related content config
    [params.page.related]
      enable = true
      count = 5

# Site verification code config for Google/Bing/Yandex/Pinterest/Baidu
[params.verification]
    google = ""
    bing = ""

# DoIt NEW | 0.2.10 Site SEO config
[params.seo]
    # image URL
    image = ""
    # thumbnail URL
    thumbnailUrl = ""
    # DoIt NEW | 0.4.1
    # alternate site name in Google search result
    alternateName = ["Milad Mohammadi - Home Page"]

# DoIt NEW | 0.2.0 Analytics config
[params.analytics]
    enable = false
    # Google Analytics
    [params.analytics.google]
      id = ""
      # whether to anonymize IP
      anonymizeIP = true

[menu]
  [[menu.main]]
    identifier = "projects"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "Projects"
    url = "/projects/" 
    # title will be shown when you hover on this menu link
    title = ""
    weight = 1
  [[menu.main]]
    identifier = "posts"
    pre = ""
    post = ""
    name = "Posts"
    url = "/posts/"
    title = ""
    weight = 2
  [[menu.main]]
    identifier = "tags"
    pre = ""
    post = ""
    name = "Tags"
    url = "/tags/"
    title = ""
    weight = 3
  # [[menu.main]]
  #   identifier = "categories"
  #   pre = ""
  #   post = ""
  #   name = "Categories"
  #   url = "/categories/"
  #   title = ""
  #   weight = 3
  [[menu.main]]
    identifier = "about"
    pre = ""
    post = ""
    name = "About"
    url = "/about/"
    title = ""
    weight = 4

# Markup related configuration in Hugo
[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = true
    lineNumbersInTable = true
    # false is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false
  # Goldmark is from Hugo 0.60 the default library used for Markdown
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.renderer]
      # whether to use HTML tags directly in the document
      unsafe = true
  # Table Of Contents settings
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 6

[outputs]
  home = ["HTML", "RSS", "JSON"]
#  taxonomy = ["HTML", "RSS"]

# Options for taxonomies
#[taxonomies]
#author = "authors"
#tag = "tags"

[params.search]
  enable = true
  # type of search engine ("lunr", "algolia", "fuse")
  type = "fuse"
  # max index length of the chunked content
  contentLength = 4000
  # placeholder of the search bar
  placeholder = ""
  # DoIt NEW | 0.2.1 max number of results length
  maxResultLength = 10
  # DoIt NEW | 0.2.3 snippet length of the result
  snippetLength = 30
  # DoIt NEW | 0.2.1 HTML tag name of the highlight part in results
  highlightTag = "em"
  # DoIt NEW | 0.2.4 whether to use the absolute URL based on the baseURL in search index
  absoluteURL = false
  [params.search.algolia]
    index = ""
    appID = ""
    searchKey = ""
  [params.search.fuse]
    # DoIt NEW | 0.2.12 https://fusejs.io/api/options.html
    isCaseSensitive = false
    minMatchCharLength = 2
    findAllMatches = false
    location = 0
    threshold = 0.3
    distance = 100
    ignoreLocation = false
    useExtendedSearch = false
    ignoreFieldNorm = false

# Author config
[params.author]
    name = "Milad Mohammadi"
    email = ""
    link = ""
    avatar = "/images/coding.png"
    gravatarEmail = ""

# Sitemap config
[sitemap]
  changefreq = "daily"
  filename = "sitemap.xml"
  priority = 1

